import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import "../globals.css";

const COOKIE = process.env.AUTH_COOKIE_NAME ?? "__app_auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(COOKIE)?.value;

  if (!token) {
    // Middleware sudah menambahkan ?next, jadi cukup redirect polos.
    redirect("/login");
  }
  return (
    <SidebarProvider>
      <AppSidebar />

      <main className="bg-[#FAFAFC] w-full relative flex-1">{children}</main>
    </SidebarProvider>
  );
}
